### ISSUE TITLE
Bot incorrectly counting maintainer shipit comments

### ISSUE THREAD

**Issue by mattclay** [ansible/ansibullbot#1034]
The bot appears to have a case sensitivity issue when counting maintainer `shipit` comments.

Here are two example PRs:

https://github.com/ansible/ansible/pull/44719
https://github.com/ansible/ansible/pull/44723

The `bot_status` comment shows the following:

> lib/ansible/modules/cloud/linode/linode.py
> support: community
> maintainers: intheclouddan lwm zbal

Yet when counting `shipit` it appears to have a case matching problem:

> shipit_actors (maintainers or core team members): lwm
> shipit_actors_other: InTheCloudDan

The user "InTheCloudDan" is a known maintainer per the bot status, yet they are counted as other.

**Comment by lwm** [comment]
If it helps, I was added as an additional Linode module maintainer **after** the pull request was submitted.

**Comment by lwm** [comment]
PS. Can I get those PRs merged!? :sweat_smile:

**Comment by webknjaz** [comment]
@mkrizek it looks like this one I've shown you, was another instance related to issue described. https://github.com/ansible/ansible/pull/45295#issuecomment-420626198

**Comment by pilou-** [comment]
Problem with #44719 #44723 was the [wrong case](https://github.com/ansible/ansible/pull/44719#issuecomment-421300962) in `BOTMETA.yml` of one maintainer.

The issue encountered with #45295 seems unrelated.

* jtanner wrote on #ansible-devel (2018-08-21):
  > rather than me going through and lowercasing all name checks in the bot code and probably missing many or breaking a bunch of code
* Erroneous cases will be fixed by ansible/ansible#46051.

@gundalow Is there something to do for this issue ?

**Comment by gundalow** [comment]
GIven @pilou- comments above I'm closing this
