### ISSUE TITLE
Report a bug

### ISSUE THREAD

**Issue by xuxiaowei0512** [ansible/ansibullbot#1261]
1. Tow shipits do not trigger an ‘automerge’ after 3 hours.
2. 'bot_status'  comments info twice.
See PR ansible/ansible#60412

**Comment by mkrizek** [comment]
1. https://github.com/ansible/ansible/pull/60412#issuecomment-520658721 - this comment indicates that `automerge shipit test failed` since there was only one shipit at that time. https://github.com/ansible/ansible/pull/60412#issuecomment-520676379 - additional shipit was added which led to `automerge` label being added and consequently bot merged the PR.

2. This is known issue, see https://github.com/ansible/ansibullbot/issues/1253

I am going to close this per above.
