### ISSUE TITLE
Add label for issues suggested for new contributors

### ISSUE THREAD

**Issue by robinro** [ansible/ansibullbot#203]
Ansible has quite a few open issues that are suitable for new contributors to start with. I'd like to propose a label like `first-timers-only` or `new-contributors` that highlights issues that are a good starting point.

We have `waiting_on_contributor`, but that quite often is not "low hanging fruit", but the opposite. And it's also more about the process than the content of the issue.

Other projects use something similar:
* https://gitlab.com/gitlab-org/gitlab-ce/issues?label_name%5B%5D=first-timers-only
* http://www.firsttimersonly.com/
* https://github.com/facebook/flow/labels/Effort%3A%20easy
* https://github.com/dotnet/roslyn/labels/Up%20for%20Grabs
* http://up-for-grabs.net/#/

This label (and a link to the github search for that label) should then be highlighted early in the dev guide. The dev guide could use a fancy "frontpage" btw.

Ansibullbot should have a command to add that label to any open issue.

**Comment by jctanner** [comment]
@robinro i think we have generally used "easyfix" for those scenarios.

**Comment by robinro** [comment]
In ansible/ansible 7 of 1000 issues have that label, I would suggest to have 30-50 for people to choose from. Anyhow I didn't find that label mentioned anywhere, so this becomes a docs feature request.

**Comment by bcoca** [comment]
I tend to just 'fix' anything i find that I would label 'easyfix'

**Comment by gundalow** [comment]
We have 17 issues with this label (across the three repos)

Once we've agreed on the name we should
* http://docs.ansible.com/ansible/community.html#contributing-code-features-or-bugfixes
* Add some other items to the list
* Email out the search and list of current items (in the three repos) to the Google Dev Group
 * Emailing the list rather than just the search URL means people are more likely to see stuff and go "I could fix that"

**Comment by jctanner** [comment]
Resolved by https://github.com/ansible/ansibullbot/pull/619
