### ISSUE TITLE
missing shippable test result comments

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#513]
mattclay [11:18 PM] 
@jctanner I've noticed several PRs that the bot seems to not be commenting on when CI failures occur, such as this: https://app.shippable.com/github/ansible/ansible/runs/21001/1/tests

**Comment by jctanner** [comment]
Looks like a shippable problem to me:

```
[jtanner@fedmac ansibullbot]$ curl --header "Authorization: apiToken XXXXX" https://api.shippable.com/runs/21001 ; echo ""                                                                                                     
{"logType":"verbose","methodName":"runs|getById|callerId:XXXXXXX|runId:21001|_getById","id":4004,"message":"runs GET failed for id: 21001"}
```

**Comment by jctanner** [comment]
@mattclay ^

**Comment by jctanner** [comment]
Same result with the test/utils/shippable/download.py script ...
```
[jtanner@fedmac shippable]$ ./download.py 21019 --console-logs                                                                 
Traceback (most recent call last):
  File "./download.py", line 296, in <module>
    main()
  File "./download.py", line 157, in main
    raise Exception(response.content)
Exception: {"logType":"verbose","methodName":"runs|getById|callerId:XXXXX|runId:21019|_getById","id":4004,"message":"runs GET failed for id: 21019"}

[jtanner@fedmac shippable]$ ./download.py 21019 --all
Traceback (most recent call last):
  File "./download.py", line 296, in <module>
    main()
  File "./download.py", line 157, in main
    raise Exception(response.content)
Exception: {"logType":"verbose","methodName":"runs|getById|callerId:XXXXX|runId:21019|_getById","id":4004,"message":"runs GET failed for id: 21019"}
```

**Comment by mattclay** [comment]
The Shippable runs API needs a run ID (24-digit hex value) not the 5-digit run number.

**Comment by mattclay** [comment]
In the last 2 - 3 days Shippable changed the status URLs for pull requests. Instead of containing the job ID, they now contain the organization, project and run number. You can use URLs of the following format to look up runs using this new information:

https://api.shippable.com/runs?providerIds=562dbd9710c5980d003b0451&subscriptionOrgNames=ansible&projectNames=ansible&runNumbers=21095

The `providerIds` portion of the query string is for limiting the query to GitHub. I wasn't able to find a query string which allowed for querying based on the provider name or URL to make it more readable.

NOTE: The bot will need to understand both the old and new status URL format if it will be looking at older CI runs as well.
