### ISSUE TITLE
wildcard matching in BOTMETA.yml

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#688]
https://github.com/ansible/ansible/pull/27551 adds in lines such as
`lib/ansible/plugins/action/junos:` which should match `junos_config.py` and `junos.py` in that directory

**Comment by pilou-** [comment]
A workaround: move `junos_config.py` and `junos.py` in a dedicated `lib/ansible/plugins/action/junos` directory. Maintainers defined at a given directory should be propagated to child (#767, precisely: https://github.com/ansible/ansibullbot/pull/767/commits/828d21ff66f7cbc0adc8cdda11462fefbb2ffd68 and https://github.com/ansible/ansibullbot/pull/767/commits/ef032fbfc55f41f34ede2d7b371914f1b9e73bd5).

**Comment by gundalow** [comment]
If this is still broken then this needs fixing ASAP as I assumed this worked in https://github.com/ansible/ansible/pull/44903

**Comment by pilou-** [comment]
AFAIK it is broken since end of 2017 (tested with current `BOTMETA.yml`):

1. It appears `FileIndexer` is able to identify expected labels for `lib/ansible/plugins/action/junos_config.py` using [`FileIndexer.find_component_matches_by_file`](https://github.com/ansible/ansibullbot/blob/d1e0e55277e712bac4745a6d17ca7caaaca5f575/ansibullbot/utils/file_tools.py#L172) method:
    ```
    >>> self.file_indexer.find_component_matches_by_file(['lib/ansible/plugins/action/junos_config.py'])
    [{'owners': ['Qalthos', 'ganeshrn', 'rcarrillocruz', 'trishnaguha', 'gdpak', 'justjais'], 'labels': ['action', 'ansible', 'junos', 'lib', 'networking', 'plugins'], 'notify': [], 'supported_by': 'core', 'filename': 'lib/ansible/plugins/action/junos_config.py'}]
    ```
    but call to this method [has been removed](https://github.com/ansible/ansibullbot/blob/9ea036fb76f2047e7c5a29b8450a3a05b8432c84/ansibullbot/triagers/plugins/component_matching.py#L243-L582) with the [new component matching engine](#795).
    Note that `FileIndexer` method because it [checks if filenames start with BOTMETA paths](https://github.com/ansible/ansibullbot/blob/d1e0e55277e712bac4745a6d17ca7caaaca5f575/ansibullbot/utils/file_tools.py#L141).

2. [`AnsibleComponentMatcher.get_meta_for_file`](https://github.com/ansible/ansibullbot/blob/d1e0e55277e712bac4745a6d17ca7caaaca5f575/ansibullbot/utils/component_tools.py#L986) doesn't retrieve the expected labels:
    ```
    >>> component_matcher.get_meta_for_file('lib/ansible/plugins/action/junos_config.py')
    {'committers': [], 'name': 'junos_config', 'deprecated': False, 'repo_filename': 'lib/ansible/plugins/action/junos_config.py', 'support': 'core', 'labels': [], 'namespace': None, 'supported_by': 'core', 'ignore': [], 'maintainers': [], 'notify': [], 'authors': [], 'topic': None, 'namespace_maintainers': [], 'assign': [], 'subtopic': None}
    ```
3. I checked that bot behavior with this test pull request created on ansible repository : https://github.com/ansible/ansible/pull/45326 (`junos` label isn't added when `junos_config.py` is updated).

**Comment by mkrizek** [comment]
FYI I just started working on this.
