### ISSUE TITLE
authors line format edgecase

### ISSUE THREAD

**Issue by jctanner** [ansible/ansibullbot#704]
https://github.com/ansible/ansible/pull/23127

```
author: Tomas Karasek <tom.to.the.k@gmail.com>, Matt Baldwin <baldwin@stackpointcloud.com>, Thibaud Morel l'Horset <teebes@gmail.com>
```

1. make sure that is parsed correctly
2. check if the blame data can correlate those emails to github nicks

**Comment by gundalow** [comment]
Do we want `validate-modules` to enforce the correct format?

**Comment by pilou-** [comment]
@gundalow I don't see any reason to not enforce the correct format ([`First Last (@githubid)`](http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_documenting.html#documentation-block)).

A lot of people are using `First Last <first@last.example>`: should the format be updated in order to allow to specify an email or should the email be put in the copyright block ?

**Comment by bcoca** [comment]
(@githubnick) <= missing from that format, it should be required on new entries ... we need to update existing

**Comment by bcoca** [comment]
also, it can be , separated string and/or yaml list

**Comment by pilou-** [comment]
comma separated format is used but is not documented in [dev_guide](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/dev_guide/developing_modules_documenting.rst#documentation-block). Should it be added ?
