### ISSUE TITLE
Ansibullbot re-sends all comments when an issue is moved, loses history dates

### ISSUE THREAD

**Issue by grizzlyanderson** [ansible/ansibullbot#762]
This morning https://github.com/ansible/ansible-modules-core/issues/5522 was moved to https://github.com/ansible/ansible/issues/29510  All of the comments on the issue were moved, but their data/time stamp was changed that of the original issue 2016-11-07T21:17:52Z, even though some were as recent as 7 days ago. The original comment dates should be preserved so that the timeline of issues/comments is apparent.  The ansibillbot then proceeded to re-send EVERY message to anyone mentioned in them. It should ONLY send the move notification.

**Comment by jctanner** [comment]
Comments are copied by design to preserve the history of the issue and and related bot commands. 

The github api doesn't allow for setting the comment date, so your request to keep the date is impossible to acheive (although the bot is putting the original timestamp in the comment body).

The bot does not "send messages", but bot makes comments and github's backend parses out the '@' symbols and notifies those people. We also want that to occur because those issues were sitting in the module repos for many months now without any activity.
