### ISSUE TITLE
owner_pr not set for module_utils

### ISSUE THREAD

**Issue by gundalow** [ansible/ansibullbot#776]
https://github.com/ansible/ansible/pull/30404 by amuraleedhar updated a single file `lib/ansible/module_utils/cnos.py`

**https://github.com/ansible/ansible/blob/devel/.github/BOTMETA.yml**
```
  $module_utils/cnos.py:
    maintainers: dkasberg amuraleedhar
    labels: networking
```

The bot correctly notified dkasberga and added `label:networking` though `label:owner_pr` was not added.

Is this because `module_utils` implies `support:core`?

**Comment by pilou-** [comment]
No, this is because:
1. `owner_pr` is set in `shipit` plugin [but only when a module match](https://github.com/ansible/ansibullbot/blob/935176b01e2e0f55acf6c9a584d99bb5a56de119/ansibullbot/triagers/plugins/shipit.py#L218), namely only when pull request update a file below `lib/ansible/modules`.
2. meta[`module_match`] isn't set, [`is_module_util` is set](https://github.com/ansible/ansibullbot/blob/14db851e3a1918c3fa41b67d12049068d7e49f21/ansibullbot/triagers/plugins/component_matching.py#L121).

Related: #746

**Comment by gundalow** [comment]
I personally don't have a need to for `supported_by` on module_utils.

I use the `label:owner_pr label:networking` as a way of saying "This person knows this area of code and should be fast tracked through the review process."

Does/should `label:owner_pr` only be added if *every* file in the PR is owned by the user?

**Comment by pilou-** [comment]
`owner_pr` is set when the submitter is a maintainer of the matched module.
If the pull request updates many modules, the [last one will match](https://github.com/ansible/ansibullbot/blob/master/ansibullbot/triagers/plugins/component_matching.py#L136-L155), the pull request will be labeled with `owner_pr` if the submitter is a maintainer of the last one matched module.

**Comment by pilou-** [comment]
@gundalow wrote:
> Does/should label:owner_pr only be added if every file in the PR is owned by the user?

Here is pull request adding `owner_pr` label when submitter is submitter of at least one `module_utils` file: #778.

I propose to update the behavior in order to add `owner_pr` only when submitter is maintainer of all updated `modules`/`module_utils` files. @gundalow what do you think ?

**Comment by gundalow** [comment]
"I propose to update the behavior in order to add owner_pr only when submitter is maintainer of all updated modules/module_utils files" +1
