### ISSUE TITLE
to eager to 'shipit'

### ISSUE THREAD

**Issue by bcoca** [ansible/ansibullbot#783]
ansibot relabeled as shipit even after manually removing and ticket has needs_rebase and conflict merge on top.
https://github.com/ansible/ansible/pull/29108

**Comment by pilou-** [comment]
This pull request is labeled with `shipit` because two maintainers approved it (cben and yaacov).

`needs_rebase` and `needs_revision` labels don't prevent the `shipit` label to be added.

I am not sure there is a problem here:
- `shipit` label states that maintainers have approved this pull request
- the pull request won't be automerged, both `needs_rebase` and `needs_revision` prevent automerge

Would you prefer that `shipit` label be automatically removed when a pull request is labeled with `needs_rebase` and `needs_revision` ?

**Comment by bcoca** [comment]
first, if 'human' removes the shipit, the bot should 'obey' that.

 2nd since it already needs a rebase this means it will need a change in the commits, which automatically invalidates the shipit anyways. I dont think the bot should remove existing shipit, but it should not re-add it when needs_rebase nor needs_revision labels are present.

This is not an automerge issue, during triage we are supposed to view any things in the 'shipit' queue and either merge or remove it from queue ... which we cannot if the bot keeps readding them.

**Comment by pilou-** [comment]
> first, if 'human' removes the shipit, the bot should 'obey' that.

`shipit` is command but not a [label command](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md#when-to-use-label-commands): Ansibullbot ignores when a maintainer remove the `shipit` label.

> during triage we are supposed to view any things in the 'shipit' queue and either merge or remove it from queue ... which we cannot if the bot keeps readding them.

With the proposed patch (#784), a negative GithHub review (or the `needs_revision` command) will remove the pull request from the `shipit` queue: is this an acceptable workflow ?

**Comment by bcoca** [comment]
yes, that is my issue, it is ignoring the removal

as for the removal, that seems fine, i would even settle for it NOT to add it back when needs_revision is there.
