### ISSUE TITLE
Moar bot spam

### ISSUE THREAD

**Issue by astorije** [ansible/ansibullbot#847]
Hi there,

The bot spam strikes again :)
You can see on https://github.com/ansible/ansible/issues/29639#issuecomment-358477484 that a _lot_ of usernames got mentioned. Furthermore, per https://github.com/ansible/ansibullbot/issues/838 / https://github.com/ansible/ansible/pull/34338, I have been removed from BOTMETA, so I'm unclear why I keep getting mentioned.

Thanks in advance for solving this, receiving emails for this and not being able to fully opt-out is rather disruptive :)

**Comment by jctanner** [comment]
34338 was evaluated as all modules under `lib/ansible/modules/files` which is a "namespace". You were picked up because your name is in the authors list for acl.py and that turns you into a "namespaced" maintainer ...

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/acl.py#L78

**Comment by jctanner** [comment]
https://github.com/ansible/ansible/pull/35216

**Comment by astorije** [comment]
Thanks for the explanation and the PR, @jctanner!
